### ISSUE TITLE
"context" not found

### ISSUE THREAD

**Issue by vortex314** [gr3yw0lf/mqttToGraphite#1]
```
lieven@pi3:~/mqttToGraphite$ go run mqttToGraphite.go graphiteStore.go
../go/src/collectd.org/api/main.go:5:2: cannot find package "context" in any of:
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /home/lieven/go/src/context (from $GOPATH)
```
As I am a total beginner on Go language, I don't know how to remediate this, the only thing I found is that it is related to Go version 1.6 or 1.7. 
Any suggestion ?

**Comment by gr3yw0lf** [comment]
I'm able to run and build this with go 1.7.1 on linux/amd64 (output from "go version")

before the "go run", use "go build" to get all the pre-requisites, then "go run" (or "go build" to make a binary).  I've not built from a clean system for some time, so I ran this through a docker to check that all the requirements pull (go version go1.9.2 linux/amd64).

I assume from the machine name you're trying to get this to run on a Raspberry Pi? Are you looking to compile this from the Pi, or would you be looking at compiling elsewhere and copying the file to the Pi (ie. cross compile for arm) ?

There's a change coming where I set the defaults to 127.0.0.1 for the servers too.

**Comment by vortex314** [comment]
Ok, I installed go on the Raspberry pi 3 with : https://gist.github.com/konradko/a9468beb70f0fa47766f5ebf966f24e8
After this it compiled and runned.
